#!/bin/bash

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
echo "Instaling tmux pluings..."
$HOME/.tmux/plugins/tpm/bin/install_plugins

# Backup /etc/pacman.conf before chaning
sudo cp /etc/pacman.conf /etc/pacman.conf.yadm.backup

# Enable multilib repo
sudo sed -i '/#\[multilib\]/{N;s/#\[multilib\]\n#Include = \/etc\/pacman\.d\/mirrorlist/\[multilib\]\nInclude = \/etc\/pacman.d\/mirrorlist/}' /etc/pacman.conf

# Update system
sudo pacman -Syu

# Install all pacakges
sudo pacman -Sy ~/.config/pacman/pkglist.txt

